### ISSUE TITLE
integration of load_boundary into gen_gsg

### ISSUE THREAD

**Issue by awfgit** [AWF-GAUG/gsgsim#1]
Can we somehow integrate the load_boundary function into the gen_gsg funktion? The current load_boundary makes some problems in the shiny App. I get errors if country_code and adm_level is empty!

load_boundary should have three options:
1) if a shapefile or geometry is selected, use this one, or
2) if a country_code is selected, use this, or
3) if nothing is selected, generate a global grid (a geometry for the global landmass is required)

**Comment by awfgit** [comment]
To avoid switching between two projects all the time (gsgsim and gsg_shiny), I moved the shiny app to a subdirectory in gsgsim. 
The load_boundary function still gives an error: is.character(dsn) is not TRUE

**Comment by sebschnell** [comment]
It works on my computer. Have you pulled the current version from the repository to your computer?

**Comment by awfgit** [comment]
I pulled but forgot to build! Now its running!

**Comment by sebschnell** [comment]
Super!
