### ISSUE TITLE
Load multiple countries

### ISSUE THREAD

**Issue by lfehrma** [AWF-GAUG/gsgsim#3]
Shiny would allow to select multiple countries in the dropdown (by adding the parameter multiple = TRUE to the selectInput). However, only the first selected country is used.  Is it possible to adapt the load_boundary function such that we can use multiple polygons?

**Comment by sebschnell** [comment]
Done. It is now possible to provide a character vector with ISO codes. A loop will then download the shapes and merge them one by one. Hope shiny can handle this - depends on the output the drop down menu will generate when multiple choices are selected. If it is a character vector, everything is fine. Don't forget to pull and build :)
