### ISSUE TITLE
Reduce columns in output

### ISSUE THREAD

**Issue by awfgit** [AWF-GAUG/gsgsim#4]
The number of columns in the output KML is unreasonable high (e.g. if boundaries from GADM are used). Instead of taking all colums from the boundary layer, we should reduce this to: ID, Country, X, Y. Country should be taken from country_code.

**Comment by sebschnell** [comment]
Done

**Comment by awfgit** [comment]
Hi Sebastian, works like a charm if you select multiple countries, but gives an error if you take only one (Error in if: missing value where TRUE/FALSE needed)!

**Comment by sebschnell** [comment]
Already fixed and comes with the next commit that handles also the other issue with the empty grids.
