### ISSUE TITLE
Use of own aoi file not working

### ISSUE THREAD

**Issue by awfgit** [AWF-GAUG/gsgsim#5]
Up to now the upload of an own aoi file is not working. Problem is the readOGR function in load_boundary that cannot access the temporary file that is uploaded via shiny.

**Comment by sebschnell** [comment]
If I remember correctly, the function that handles uploads in shiny returns a data.frame with a column that holds the temporary file paths or is it only kept in the working memory. My time this week is rather limited as I’m virtually on vacation ☺.

**Comment by awfgit** [comment]
Problem was solved by Nils already!

**Comment by sebschnell** [comment]
Just saw that Nils already solved the problem, thank you. Could you also update the documentation above the load_boundary() function in utilities.R. There it is still written that readOGR() from rgdal is used.
